US-CBP/cbp-theme

- app/kitchensink/index.html
- app/styles/custom/_alerts.scss
- app/styles/custom/_variables.scss
and add aria to alerts and notification
> Issue #42: accessibility fix on notification, fixes: extend alert scss

- package-lock.json
- package.json
@davezen1 @mkayan This was preventing me from even completing an `npm install` on our Windows workstations.
> Use newer node-sass so us poor windows users can help

- app/styles/custom/_forms.scss
- app/styles/custom/_switch.scss
Extracting `.switch` class from `custom/_forms.scss` into new `custom/_switch.scss` with `@import './switch';` inside `custom/_forms.scss`
This is to resolve https://github.com/US-CBP/ngx-cbp-theme/issues/37
> refactored styles of on/off switch component

- kitchensink/index.html
- kitchensink/kitchensink.css
- src/styles/custom/_navbar.scss
Fixes app-header wrapping issue
Run locally
By resizing browser
165
No
> Fix app header wrapping issue

- package-lock.json
- package.json
- src/js/app-inputmasks.js
Fixes issue of the Datepicker with the placeholder.
Checkout and run locally
Open console and test picking a date under the Date Picker With Placeholder Label
195
No
> Fix to the datepicker issue.

- kitchensink/index.html
Adds for attribute to label tags for matching radio buttons/checkboxes that were missing them.
See markup
#45, 
No
No
> fix-theme-issue-45

- src/js/app-char-limit.js
Displays the correct count of char as user input/delete
Delete, input or paste random text in the **Input Character Limits
Textfield** area.
I understand issue was closed but prior to submitting PR I see that problem still exists, count was not displaying correct char count.
#196 
No
No
> Fixes theme issue 196

- README.md
Updates README file.
jQuery was upgraded from v2.2.4 to v3.3.1 due to some security vulnerabilities with older version.
#192 
No
> Updated README to indicate jQuery 3.x+ is recommended.

- package-lock.json
- src/styles/custom/_globals.scss
- Addresses Issue 236 with tooltips not wrapping properly
- in _Globals.scss
- in F12 Developer mode. Overload a tooltip with a single long string
- N/A
- TCFU-1572
- No
- No
> Issue 236 - Proper Tooltip Wrap

- package-lock.json
- src/styles/custom/_globals.scss
- Addresses color Issue with Labels being links
- Globals.scss
- apply the label class to "a" tag and verifiy colors.
- TCFU-1571
> Label Links also preserve color

- src/styles/custom/_variables.scss
- Address gray coloring in the CBP Theme
- Variables.scss
- TCFU-1602
> made changes to grays in theme

- package-lock.json
- package.json
- updates the Roboto-Font-Face Library to remove extranious fonts from the build 
- run `npm install` of the project and verify only woff and woff2 files are in the fonts folder
- TCFU -1737
> updated roboto-font-face library

- src/styles/vendor/_material_cards.scss
Updates to MDL-Cards. 
Look at _material_cards.css inside the src/style/vendor folder.
Run project locally.
Main changes where done to bg-color, hover/focus state
TCFU 1981.
> Tcfu 1981 update to mdl cards

- package-lock.json
updates package-lock.json
Made prior changes but had not generated new package-lock.json file.
> TCFU-2081: newly generated package-lock.

- kitchensink/index.html
- src/styles/custom/_carousel.scss
Add some responsive updates for the new carousel and simple edits to the index file.
Looking at the src/styles/custom/_carousel.scss and kitchensink/index.html files
Checking the responsive of the carousel component within all three major browsers.
The addition of this new component is in response to a user request.
n/a
n/a
n/a
no
> resposive edit to new carousel and index file

- ds-css/.pa11yci
- ds-css/package-lock.json
- ds-css/package.json
Setup an automated process for 508 accessibility testing using a combination of '**pa11y-ci**' && 'p**a11y-ci-reporter-html**' tools.  
This is currently just testing the css-framework's served files and placing any errors within a file called 'pa11y-ci-results.json' file, from which the results are also transferred to a file called 'localhost-9000.html' to use for local display.
In addition, we may want to further integrate "pa11y-ci" with Travic CI for testing multiple files in parallel,
( https://andrewmee.com/posts/automated-accessibility-testing-node-travis-ci-pa11y/ )
Check out the edited p**ackage.json file**, and new '**.pa11yci'** file.
Steps:
1. 'npm run build-local'
2. once step 1 is complete, then open new CLI window
3. within new CLI window, 
- 'npm run 508-test'
(Runs 508 …
> setup initial automated 508 accessibility testing process for local build

- .travis.yml
- cypress.json
- cypress/integration/home_page_spec.js
- package-lock.json
- package.json
- added cypress library for functional tests and included initial test for
home page
- wired cypress with the ci process
Take a look at the package.json in the root, cypress folder, and cypress.json file
To test the build ```npm run tests:e2e ``` 
ensure that the ds ux is built 
- Is there a blog post? n/a/
- Does the knowledge base need an update? n/a
> feat: Initial add of e2e tests

- ds-css/src/styles/custom/elements/_all.scss
- ds-css/src/styles/custom/elements/table.scss
- ds-ux-guidelines/components/tables.html
- ds-ux-guidelines/css/updated-styles.css
- ds-ux-guidelines/index.html
- ds-ux-guidelines/sass/updated-styles.scss
-Adds the Table Section of the CBP Style Guide 
-Manual styling of Bulma's Table css to include a grey background color on header cells
- `ds-ux-guidelines/components/tables.html`
- `ds-css/src/styles/custom/elements/table.scss`
-N/A
-N/A
- Is there a blog post? **No**
- Does the knowledge base need an update? **No**
> DS Tables Page & Table Modification

- ds-css/src/styles/cbp-ds.scss
- ds-css/src/styles/custom/components/_all.scss
- ds-css/src/styles/custom/components/menu.scss
- ds-ux-guidelines/components/buttons.html
- ds-ux-guidelines/components/tables.html
- ds-ux-guidelines/css/updated-styles.css
- ds-ux-guidelines/js/scripts.js
- ds-ux-guidelines/sass/styles.scss
- ds-ux-guidelines/sass/updated-styles.scss
Modifies the sidebar menu component from bulma to include CBP-colors for background-color, color, font-weight/size, and hover.
**Menu component**
`ds-css/src/styles/custom/components/menu.scss`
**Tab functionality (Probably will be changed soon with new framework**
`ds-ux-guidelines/components/tables.html` line 137-145
`ds-ux-guidelines/js/scripts.js` line 61-78
N/A
Second PR attempt
N/A
- Is there a blog post? 
No
- Does the knowledge base need an update? 
Need to make changes for Menu component in the UX Guidance.
> Modify sidebar

- .gitignore
- .travis.yml
- README.md
- cbp-theme/package.json
- ds-css/package-lock.json
- ds-css/package.json
- package-lock.json
- package.json
- publish.sh
- cleanup of author names
- added README
- minor .gitignore additions dist, cypress, etc
- added dist prepare task to copy readme, proper version, and package.json to dist in root
- refactored npm css, website tasks names
- add arguments to automate publishing to npm on a tag via travis and encrypted npm token with beta tag
This helps automated the process of npm publishing via Travis CI
take a look at the package.json, .travis.yml, publish.sh and 
https://docs.travis-ci.com/user/deployment/npm/
once merged we will test using npm version which will create a tag and should kick off a build plus publish to npm
- Does the knowledge base need an update? We will need to update the README for developers wishing to understand publishing the design system
> feat: automated npm publishing

- ds-ux-guidelines/src/pages/foundation/grid.js
- ds-ux-guidelines/src/pages/foundation/layouts.js
-Added Grid & Layouts Page with placeholder text (WIP)
- `ds-ux-guidelines/src/pages/foundation/grid.js`
- `ds-ux-guidelines/src/pages/foundation/layouts.js`
- Currently does not have any content.
-N/A
> create grid & layouts pages

- .travis.yml
- End of life for node 8 has been reached upgraded to node 10
Upgrades Travis CI's Node version to 10
.travis.yml
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
Check that the logs in the build in Travis CI show node 10
n/a
n/a
> chore: upgrade travis node version to 10

- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
- ds-ux-guidelines/src/ds-components/navigation/navigation.js
- ds-ux-guidelines/src/pages/components/tables.js
- ds-ux-guidelines/src/pages/foundation/grid.js
- ds-ux-guidelines/src/pages/foundation/layouts.js
- ds-ux-guidelines/src/pages/foundation/typography.js
- fixed version dropdown menu
- added small spacing changes on all functional pages that broke from last commit
- added formatting class from ux-ds-guidelines v1 `.tables-usage--box` (used for the height of boxes in the pros & cons section in tables page)
- `ds-ux-guidelines/src/ds-components/navigation/navigation.js`
-  `components/tables.js`, `foundation/grid.js`, `foundation/layouts.js`, `foundation/typography.js`
- manual inspection of tables, typography, layout, and grid pages (for consistent spacing)
-N/A
-N/A
- Is there a blog post? No
- Does the knowledge base need an update? No
> Fix Version Dropdown, Small Spacing Changes

- ds-ux-guidelines/src/ds-components/navigation/navigation.js
Fix issue where you could not close out of the dropdown unless you click on the button again.
`ds-ux-guidelines/src/ds-components/navigation/navigation.js`
-  Click on the dropdown button to make sure it opens/closes properly.
N/A
N/A
N/A
- Is there a blog post? No
- Does the knowledge base need an update? No
> Dropdown Menu Close Fix

- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
- ds-ux-guidelines/src/pages/foundation/typography.js
Adds the current typography draft to the style guide. Minor additions to the css.
typography.js
N/A
N/A
N/A
N/A
> added typography WIP

- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
Small spacing change for sections
`ds-common-styles.scss`
Check page to see spacing
N/A
N/A
Small Example: 
**Before:**
**After:**
> added spacing for sections

- .editorconfig
Adds initial editorconfig file
.editorconfig at root and ensure you understand the setttings: https://editorconfig.org/
> chore: initial add of editorconfig

- ds-ux-guidelines/src/html.js
Added Tota11y to ds-ux-guidelines
`html.js`
Test out functions with icon on the bottom left of the screen.
N/A
N/A
> Add Tota11y CDN

- ds-ux-guidelines/src/pages/foundation/typography.js
finish adding the rest of the content to the typography page.
`typography.js`
Compare with Confluence document to see if the content is the same
Added a couple TODO's (adding images, adding dropdown toggle, etc.)
N/A
N/A
> Final Additions to Typography Content

- ds-ux-guidelines/.babelrc.json
- ds-ux-guidelines/src/ds-components/content-header/contentHeader.js
- ds-ux-guidelines/src/ds-components/navigation/navigation.js
- ds-ux-guidelines/src/pages/get-started/getStarted.js
added a "Get Started" page & added section in the navigation.
`navigation.js` - added ternary operator to create links that do not have a sub category. 
`get-started/getStarted.js` - created new page
Click on "Get Started" in the navigation & check to see if the page loads.
Not sure where the page should be located in the file structure. Can discuss as needed.
N/A
> added initial get started page

- ds-ux-guidelines/src/ds-components/header/header.js
fixes GitHub link in header
header.js
Run the DS website
> fix: updated GitHub link in header of DS

- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
- ds-ux-guidelines/src/ds-components/layout/layout.scss
- ds-ux-guidelines/src/pages/components/tables.js
- ds-ux-guidelines/src/pages/foundation/typography.js
Adjust spacing wrapper to accommodate tags without a `<section>` tag, and made general improvements to the flow of the typography page. 
`ds-common-styles.scss`
`typography.js`
Compare the spacing between the web page and css values. 
N/A
N/A
N/A
> improved spacing wrapper, made qol adjustments to typography page

- ds-ux-guidelines/src/ds-components/codeSnippet/codeSnippet.scss
- ds-ux-guidelines/src/ds-components/navigation/navigation.scss
- ds-ux-guidelines/src/pages/foundation/typography.js
Temporary override for Bulma's code tag css that conflicted with prismjs. Also made slight modifications for typography.js that fixes some heading hierarchy accessibility issues.
`ds-common-styles.scss`, `typography.js`
See that the current code snippets in typography.js and layout.js are displayed correctly.
N/A
N/A
N/A
> Temp. Bulma <code> override

- ds-ux-guidelines/src/ds-components/codeSnippet/codeSnippet.js
- ds-ux-guidelines/src/ds-components/codeSnippet/codeSnippet.scss
- ds-ux-guidelines/src/ds-components/navigation/navigation.js
- ds-ux-guidelines/src/pages/components/tables.js
- ds-ux-guidelines/src/pages/foundation/iconography.js
- ds-ux-guidelines/src/pages/foundation/typography.js
Adds Iconography page to the style guide.
`iconography.js`
Check if the iconography page displays properly & is linked correctly in the navigation menu
N/A
N/A
N/A
> Add Iconography Page

- ds-css/src/styles/custom/base/generic.scss
- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
- ds-ux-guidelines/src/ds-components/content-header/contentHeader.js
- ds-ux-guidelines/src/ds-components/ds-tabs/tabs.js
- ds-ux-guidelines/src/ds-components/ds-tabs/tabs.scss
- ds-ux-guidelines/src/pages/components/tables.js
- ds-ux-guidelines/src/pages/foundation/iconography.js
- ds-ux-guidelines/src/pages/foundation/layouts.js
- ds-ux-guidelines/src/pages/foundation/typography.js
- ds-ux-guidelines/src/pages/get-started/getStarted.js
- Separates tab content within each page
- Spacing changes for the Get Started page
- Lightened grey color for tab
- `typography.js`, `layouts.js`, `grids.js`, `tables.js`, `getStarted.js`
- Manually navigate through each existing page to check that the tab is directing to the right content
- Need to adjust the right margin of the grey line for tabs
- Will delete tab component & existing references after PR review
> Separate Tab Content

- ds-css/package-lock.json
- ds-css/package.json
- ds-css/src/styles/custom/grid/cbp-grid.scss
- package-lock.json
- package.json
Removes row gap from CSS Grid
Download and run branch locally.
It is easier to view in Firefox, once it's run locally change the main div from "cbp-ds-grid" to "cbp-grid" and the gaps in row should be removed. You should only see a gap in the columns.
N/A
N/A
N/A
N/A
N/A
> Gap update

- ds-css/src/styles/custom/base/generic.scss
- ds-ux-guidelines/src/ds-common-styles/ds-common-styles.scss
- ds-ux-guidelines/src/ds-components/ds-tabs/tabs.js
- ds-ux-guidelines/src/ds-components/ds-tabs/tabs.scss
- ds-ux-guidelines/src/ds-components/layout/layout-development.scss
- ds-ux-guidelines/src/ds-components/layout/layout.scss
- ds-ux-guidelines/src/ds-components/navigation/navigation.js
- ds-ux-guidelines/src/pages/foundation/interactivity.js
- ds-ux-guidelines/src/pages/index.js
- Fixes scroll-bar alignment in the content pages / clipping issues
- Experimental change to tab styling on `interactivity.js`
- small ux changes- margin for content, font weight on h2 
- cleaned up sidenav, added asterisks to sections that don't have content (did not remove some of them so that we can test 404 pages at a later date)
- Go to any foundation page and check to see if the scrollbar is displayed properly.
- Manually check each functional page on the side nav
- The other sections besides Interactivity have the old tab styling. Will discuss with team after pushes have been changed to see which one they prefer.
> fixed scroll bar display issue, experimental tab style change

- ds-css/src/styles/custom/grid/_all.scss
- ds-css/src/styles/custom/grid/cbp-grid.scss
- ds-css/src/styles/custom/grid/grid-utilities.scss
- ds-ux-guidelines/src/ds-components/layout/layout.scss
- ds-ux-guidelines/src/pages/test-page/test-page.js
- ds-ux-guidelines/src/pages/test-page/test-page.scss
Adds css grid utility classes.
1. Download repo and run npm run css:init and npm run css:build scripts.
2. Run npm run website:init and npm run website:build.
Run locally from ds-ux-guidlines and use test-page/test-page to play with utility classes to ensure that they work correctly.
N/A
N/A
N/A
N/A
> Grid utilities

- README.md
- ds-css/README.md
- ds-ux-guidelines/README.md
Updated readme to better reflect current development status
README.md in root, `ds-ux-guidelines`, and `ds-css`
Review readme and check if markdown is formatted correctly.
> Update Readme 

- ds-css/package-lock.json
- ds-ux-guidelines/package-lock.json
- ds-ux-guidelines/package.json
- ds-ux-guidelines/src/pages/test-page/test-page.js
- ds-ux-guidelines/src/pages/test-page/test-page.scss
This pull request adds a test page, for testing ds-css updates.
Download repo, npm install, and then run locally.
Visit http://localhost:8000/test-page/test-page and ensure that the page is showing correctly.
N/A
N/A
N/A
N/A
N/A
> Initial test-page layout

- ds-css-v2/boilerplate/index.html
- ds-css-v2/demo-pages/card-archetype/index.css
- ds-css-v2/demo-pages/card-archetype/index.html
- ds-css-v2/styles/sass/cbp-grid/_cbp-grid-sizing.scss
This pull request adds "xl" gird class for largest viewports
Download branch and check boilerplate index.html file. Check added **cbp-grid-col-6-xl** class, and also play around with different column widths to see if there are any issues.
Yes
N/A
N/A
N/A
N/A
N/A
> Updated grid classes to include 'xl' for largest viewport.

- ds-css-v2/demo-pages/card-archetype/index.css
Changes the border radius of the cards in the card archetype demo page to be 5px. 
> changed border radius of cards to be 5px

- ds-css-v2/demo-pages/card-archetype/index.css
- ds-css-v2/demo-pages/card-archetype/index.html
updated recently updated/added icons on the first and second cards.
> Modify Recently Updated/Added icons 

- ds-css-v2/demo-pages/card-archetype/index.css
- ds-css-v2/demo-pages/card-archetype/index.html
change the text on the filter button to cbp-text-button (all caps)
removed margin-right on the buttons
> Card archetype modify filter button

- ds-css-v2/demo-pages/card-archetype/index.css
- ds-css-v2/demo-pages/card-archetype/index.html
gives hover and pressed states to the favorites functionality
changed icon size from 26px to 18px
> Card archetype modify favorites icon

- ds-css-v2/demo-components/cbp-accordion/index.css
- ds-css-v2/demo-components/cbp-accordion/index.html
- ds-css-v2/js/cbp-components-js/cbpAccordion.js
- ds-css-v2/styles/sass/cbp-components/accordion/accordion.scss
- Code updates for accordion component in `/ds-css-v2` for hover/focus states
- `/ds-css-v2/demo-components/cbp-accordion`
- `/ds-css-v2/styles/sass/cbp-components/accordion/accordion.scss`
- Build locally and run accordion component demo page with `live-server` 
- Media queries `min-widths` for desktop were chosen based on the size in which the design look and feel breaks. 
- n/a
n/a
n/a
> chore: hover/focus code updates for accordion component

- ds-css-v2/demo-components/cbp-expand/index.html
- ds-css-v2/index.html
- ds-css-v2/js/cbp-components-js/cbpExpand.js
- ds-css-v2/styles/sass/_uswds-theme-custom-styles.scss
- ds-css-v2/styles/sass/cbp-components/expand/expand.scss
- ds-css/package-lock.json
1. Expand component for DS Archetypes
1. Run locally and open and close the component. All code changes are in `/ds-css-v2` directory.
1. Open and close the expand component in both mobile and desktop view
1. n/a
1. n/a
1. n/a
> Expand component

- ds-css-v2/demo-components/cbp-modal/index.html
- ds-css-v2/index.html
- ds-css-v2/js/cbp-components-js/cbpModal.js
- ds-css-v2/styles/sass/_uswds-theme-custom-styles.scss
- ds-css-v2/styles/sass/cbp-components/modal/modal.scss
- Modal component for the Design System 
- `/ds-css-v2/demo-components/cbp-modal`
- `/ds-css-v2/js/cbp-components-js/cbpModal.js`
- `/ds-css-v2/styles/sass/modal/modal.scss`
- Run locally and check the components table for 'Modal'
- n/a
> Modal component

- ds-css-v2/demo-components/cbp-overflow-menu/index.html
- ds-css-v2/index.html
- ds-css-v2/js/cbp-components-js/cbpOverflowMenu.js
- ds-css-v2/styles/sass/_uswds-theme-custom-styles.scss
- ds-css-v2/styles/sass/cbp-components/overflow-menu/overflow-menu.scss
- ds-css-v2/styles/sass/cbp-theme-settings/_cbp-colors.scss
- ds-css-v2/styles/sass/cbp-theme-settings/_cbp-variables.scss
- Overflow Menu component
- `/ds-css-v2/demo-components/cbp-overflow-menu/index.html`
- `/ds-css-v2/js/cbp-components-js/cbpOverflowMenu.js`
- `/ds-css-v2/styles/sass/cbp-components/overflow-menu/overflow-menu.scss`
- Run locally and check components against mock ups
- n/a
- n/a
- n/a
> Overflow menu component
